KCPQ_Project/objects/KCPQ_Quick_Link__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Labels__c</fullName>
        <label>Labels</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Updated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Link__c</fullName>
        <label>Link</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <label>Quick Link</label>
    <nameField>
        <label>Quick Link Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quick Links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

KCPQ_Project/classes/KCPQ_QuickLinksCompCtrl.cls
public class KCPQ_QuickLinksCompCtrl {
	
    @AuraEnabled
    public static String getInitializeQuickLinkWrapper(){
        return JSON.serialize(new List<KCPQ_QuickLinksWrapperCtrl>());
    }
    
    @AuraEnabled
    public static List<KCPQ_QuickLinksWrapperCtrl> getQuickLinkWrapper(String quickLinkJSONStr){
        List<KCPQ_QuickLinksWrapperCtrl> quickLinksLst = (List<KCPQ_QuickLinksWrapperCtrl>)JSON.deserialize(quickLinkJSONStr, List<KCPQ_QuickLinksWrapperCtrl>.class);
        for(KCPQ_Quick_Link__c quickLink : [SELECT Id, Name, Description__c, Link__c, Order__c, isActive__c, Labels__c 
                                            FROM KCPQ_Quick_Link__c WHERE isActive__c = true ORDER BY Order__c ASC]){
        	quickLinksLst.add(new KCPQ_QuickLinksWrapperCtrl(quickLink));
        }
        return quickLinksLst;
    }
    
    /*@AuraEnabled
    public static String getpathprefixURL(){
        return site.getpathprefix();
    }*/
}