KCPQ_Project/objects/KCPQ_Quick_Link__c.object
<CustomObject>
    <fields>
        <fullName>Link__c</fullName>
        <label>Link</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <label>Quick Link</label>
    <nameField>
        <label>Quick Link Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quick Links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

KCPQ_Project/classes/KCPQ_QuickLinksCompCtrl_Test.cls
@isTest
public class KCPQ_QuickLinksCompCtrl_Test {
public static testMethod void setTestData()
    {
        Test.startTest();
        KCPQ_QuickLinksCompCtrl.getInitializeQuickLinkWrapper();
        
        KCPQ_Quick_Link__c kql= new KCPQ_Quick_Link__c();
        kql.Name='Quicklink';
        kql.Order__c=1;
        kql.Link__c='https://www.google.co.in';
        kql.isActive__c=true;
        insert kql;
        List<KCPQ_QuickLinksWrapperCtrl> qlList = new List<KCPQ_QuickLinksWrapperCtrl>();
        
        KCPQ_QuickLinksWrapperCtrl ql = new KCPQ_QuickLinksWrapperCtrl(kql);
        qlList.add(ql);
        
        KCPQ_QuickLinksCompCtrl.getQuickLinkWrapper(json.serialize(qlList));
        Test.stopTest();
    }
}