KCPQ_Project/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Exterior_Shade__c</fullName>
        <defaultValue>&quot;#a1a1a1&quot;</defaultValue>
        <label>Exterior Shade</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Interior_Shade__c</fullName>
        <defaultValue>&quot;#dddddd&quot;</defaultValue>
        <label>Interior Shade</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Image_New__c</fullName>
        <formula>IMAGE(&quot;/servlet/servlet.FileDownload?file=&quot;&amp;Product_Image_Link__c,&quot;Image Not Available&quot;,100,100)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Image New</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Image__c</fullName>
        <label>Product Image</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>isInventoryProduct__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Inventory Product?</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

KCPQ_Project/objects/SBQQ__Quote__c.object
<CustomObject>
</CustomObject>

KCPQ_Project/classes/KCPQ_Inventory_CheckCtrl.cls
public class KCPQ_Inventory_CheckCtrl {

    @AuraEnabled
    public static List<KCPQ_InventoryWrapper> getProducts()
    {
        List<Product2> products=[Select ID,Name,Product_Image__c,Product_Image_New__c,Exterior_Shade__c,Interior_Shade__c
                                 FROM Product2 where isActive=true AND isInventoryProduct__c=TRUE 
                                ORDER BY NAME LIMIT 1000];
        return KCPQ_Utility.getProductsInventory(products);
        
    }
    
    @AuraEnabled
    public static String  createProductQuote(String productId)
    {
        System.debug('productId...'+productId);
        String priceBookId = [Select ID,Name,Pricebook2Id from PriceBookEntry where Product2Id=:productId].Pricebook2Id;
        KCPQ_Utility.createQuote(priceBookId, null);
        SBQQ__Quote__c quoteRecord = KCPQ_Utility.createQuote(priceBookId, null);
        System.debug('quoteRecord...'+quoteRecord);
        if(quoteRecord != null)
        return KCPQ_Utility.getQuoteIdAfterAddingProduct(productId, priceBookId, quoteRecord.Id);
        else
            return null;
        
    }
        
    
}