KCPQ_Project/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Body_Style__c</fullName>
        <label>Body Style</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sedan</fullName>
                </value>
                <value>
                    <fullName>Hatchback</fullName>
                </value>
                <value>
                    <fullName>Convertible</fullName>
                </value>
                <value>
                    <fullName>SUV &amp; Crossover</fullName>
                </value>
                <value>
                    <fullName>Truck &amp; Van</fullName>
                </value>
                <value>
                    <fullName>Hybrids &amp; EVs</fullName>
                </value>
                <value>
                    <fullName>Commercial trucks</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Image__c</fullName>
        <label>Product Image</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
</CustomObject>

KCPQ_Project/classes/KCPQ_SAQ_PBSelectionCtrl.cls
public class KCPQ_SAQ_PBSelectionCtrl {
    
    
    @AuraEnabled
    public static List<String> getPricebookPicklist(){
        return KCPQ_Utility.getPricebookPicklist();
    }
    
    @AuraEnabled
    public static KCPQ_QuoteWrapper createPriceBookQuote(String pricebookID){
        KCPQ_QuoteWrapper quoteWrapper=new KCPQ_QuoteWrapper();
        quoteWrapper.quoteId=KCPQ_Utility.createQuote(pricebookID, null).ID;
        return quoteWrapper;
    }
    
    public static List<Product2> getProductsForQuote(String quoteId){
        Set<Id> productIDs=KCPQ_Utility.getProductIdsFromPricebookEntries(quoteId);
        List<Product2> resultModels=[Select ID,name,Body_Style__c,Product_Image__c from Product2 where ID IN:productIDs AND IsActive=true];
        return resultModels;
    }
}